- hosts: webservers
  gather_facts: no
  tasks:
    - name: remove git
      ansible.builtin.apt:
        name: git
        state: absent
      become: yes

    - name: remove git config
      ansible.builtin.file:
        state: absent
        path: "/home/{{ item.name }}/.gitconfig"
      loop: "{{ users }}"
      become: yes
