- hosts: webservers
  tasks:
    - name: remove git
      ansible.builtin.apt:
        name: git
        state: absent
      become: yes
      when: ansible_os_family == "Debian"

    - name: remove git config
      ansible.builtin.file:
        state: absent
        path: "/home/{{ item.name }}/.gitconfig"
      loop: "{{ users }}"
      become: yes
