- hosts: webservers
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      when: ansible_os_family == "Debian"

    - name: install cowsay
      ansible.builtin.apt:
        name: cowsay
        state: latest
      become: yes
      when: ansible_os_family == "Debian"

    - ansible.builtin.shell: cowsay "Hello, from web server!"
      register: cowsay_result
      when: ansible_os_family == "Debian"

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes
      when: ansible_os_family == "Debian"

    - name: copy index.html
      ansible.builtin.template:
        src: templates/index.html
        dest: "{{ root_dir }}/index.html"
      become: yes
      when: ansible_os_family == "Debian"

    - name: update nginx config
      ansible.builtin.template:
        src: templates/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes
      when: ansible_os_family == "Debian"

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
