- hosts: webservers
  gather_facts: no
  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: yes
      tags: git

    - name: update cache apt
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags: update
